id: I0EA7C1F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:10:16+00:00'
last_modified: '2022-06-08T02:43:30.204183+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24925
  title: ཀྲུང་གོ་གུང་ཁྲན་ཏང་གི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DB88:
      image_group_id: I1KG24927
      title: ''
      total_pages: 752
      order: 1
      base_file: DB88.txt
    AC45:
      image_group_id: I1KG24928
      title: ''
      total_pages: 698
      order: 2
      base_file: AC45.txt
    '7208':
      image_group_id: I1KG24929
      title: ''
      total_pages: 618
      order: 3
      base_file: 7208.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
